[project]
name = "nllb_try"
version = "0.3.0"
description = "NLLB Gronings Tatoeba Translation Machine"
requires-python = ">=3.10,<3.12"
dependencies = [
    "transformers",
    "pandas",
    "tqdm",
    "matplotlib",
    "sacrebleu",
    "scikit-learn",
    "sentencepiece",
    "accelerate",
    "requests",
    "sacremoses",
    "torch==2.8.0+cu126",
    "torchvision==0.23.0+cu126"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]